---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-ureport-ubuntu-18.04
    image: solita/ubuntu-systemd:18.04
    dockerfile: Dockerfile.j2
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  options:
    e: ureport_git_branch=${UREPORT_VERSION}
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - destroy
lint: |
  set -e
  yamllint .
  flake8
  ansible-lint .
verifier:
  name: testinfra
