---
name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Get latest UReport version
        uses: oprypin/find-latest-tag@v1
        with:
          repository: rapidpro/ureport
          prefix: v
        id: ureport_version

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Run Molecule tests
        uses: gofrolist/molecule-action@v2
        env:
          UREPORT_VERSION: ${{ steps.ureport_version.outputs.tag }}

  release:
    name: Release
    needs:
      - test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Ansible Galaxy
        uses: robertdebock/galaxy-action@1.0.3
        with:
          galaxy_api_key: ${{ secrets.ansible_galaxy_api_key }}
